default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: db
  # username: postgres
  # password: postgres

development:
  <<: *default
  database: rent-a-car_development

test:
  <<: *default
  database: rent-a-car_test
  # host: db
  # port: 5432
